.TH "engine::scene::IQ3LevelMesh" 3 "29 Jul 2006" "LTE 3D Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine::scene::IQ3LevelMesh \- Interface for a Mesh wich can be loaded directly from a Quake3 .bsp-file.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <IQ3LevelMesh.h>\fP
.PP
Inherits \fBengine::scene::IAnimatedMesh\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~IQ3LevelMesh\fP ()"
.br
.RI "\fIdestructor \fP"
.in -1c
.SH "Detailed Description"
.PP 
Interface for a Mesh wich can be loaded directly from a Quake3 .bsp-file. 

The Mesh tries to load all textures of the map. There are currently no additional methods in this class, but maybe there will be some in later releases if there are feature requests. 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for LTE 3D Engine from the source code.
