.TH "engine::SengineCreationParameters" 3 "29 Jul 2006" "LTE 3D Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine::SengineCreationParameters \- Structure for holding advanced engine Device creation parameters.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <SengineCreationParameters.h>\fP
.PP
.SH "Detailed Description"
.PP 
Structure for holding advanced engine Device creation parameters. 

This structure is only used in the \fBcreateDeviceEx()\fP function. 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for LTE 3D Engine from the source code.
