.TH "engine::SKeyMap" 3 "29 Jul 2006" "LTE 3D Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine::SKeyMap \- Struct storing which key belongs to which action.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <SKeyMap.h>\fP
.PP
.SH "Detailed Description"
.PP 
Struct storing which key belongs to which action. 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for LTE 3D Engine from the source code.
