.TH "engine::gui::IGUISkin" 3 "29 Jul 2006" "LTE 3D Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine::gui::IGUISkin \- A skin modifies the look of the GUI elements.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <IGUISkin.h>\fP
.PP
Inherits \fBengine::IUnknown\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~IGUISkin\fP ()"
.br
.RI "\fIdestructor \fP"
.ti -1c
.RI "virtual \fBvideo::SColor\fP \fBgetColor\fP (\fBEGUI_DEFAULT_COLOR\fP color)=0"
.br
.RI "\fIreturns default color \fP"
.ti -1c
.RI "virtual void \fBsetColor\fP (\fBEGUI_DEFAULT_COLOR\fP which, \fBvideo::SColor\fP newColor)=0"
.br
.RI "\fIsets a default color \fP"
.ti -1c
.RI "virtual s32 \fBgetSize\fP (\fBEGUI_DEFAULT_SIZE\fP size)=0"
.br
.RI "\fIreturns default color \fP"
.ti -1c
.RI "virtual const wchar_t * \fBgetDefaultText\fP (\fBEGUI_DEFAULT_TEXT\fP text)=0"
.br
.RI "\fIReturns a default text. \fP"
.ti -1c
.RI "virtual void \fBsetDefaultText\fP (\fBEGUI_DEFAULT_TEXT\fP which, const wchar_t *newText)=0"
.br
.RI "\fISets a default text. \fP"
.ti -1c
.RI "virtual void \fBsetSize\fP (\fBEGUI_DEFAULT_SIZE\fP which, s32 size)=0"
.br
.RI "\fIsets a default size \fP"
.ti -1c
.RI "virtual \fBIGUIFont\fP * \fBgetFont\fP ()=0"
.br
.RI "\fIreturns the default font \fP"
.ti -1c
.RI "virtual void \fBsetFont\fP (\fBIGUIFont\fP *font)=0"
.br
.RI "\fIsets a default font \fP"
.ti -1c
.RI "virtual void \fBdraw3DButtonPaneStandard\fP (\fBIGUIElement\fP *element, const \fBcore::rect\fP< s32 > &rect, const \fBcore::rect\fP< s32 > *clip=0)=0"
.br
.RI "\fIdraws a standard 3d button pane \fP"
.ti -1c
.RI "virtual void \fBdraw3DButtonPanePressed\fP (\fBIGUIElement\fP *element, const \fBcore::rect\fP< s32 > &rect, const \fBcore::rect\fP< s32 > *clip=0)=0"
.br
.RI "\fIdraws a pressed 3d button pane \fP"
.ti -1c
.RI "virtual void \fBdraw3DSunkenPane\fP (\fBIGUIElement\fP *element, \fBvideo::SColor\fP bgcolor, bool flat, bool fillBackGround, const \fBcore::rect\fP< s32 > &rect, const \fBcore::rect\fP< s32 > *clip=0)=0"
.br
.RI "\fIdraws a sunken 3d pane \fP"
.ti -1c
.RI "virtual \fBcore::rect\fP< s32 > \fBdraw3DWindowBackground\fP (\fBIGUIElement\fP *element, bool drawTitleBar, \fBvideo::SColor\fP titleBarColor, const \fBcore::rect\fP< s32 > &rect, const \fBcore::rect\fP< s32 > *clip=0)=0"
.br
.RI "\fIdraws a window background \fP"
.ti -1c
.RI "virtual void \fBdraw3DMenuPane\fP (\fBIGUIElement\fP *element, const \fBcore::rect\fP< s32 > &rect, const \fBcore::rect\fP< s32 > *clip=0)=0"
.br
.RI "\fIdraws a standard 3d menu pane \fP"
.ti -1c
.RI "virtual void \fBdraw3DToolBar\fP (\fBIGUIElement\fP *element, const \fBcore::rect\fP< s32 > &rect, const \fBcore::rect\fP< s32 > *clip=0)=0"
.br
.RI "\fIdraws a standard 3d tool bar \fP"
.ti -1c
.RI "virtual void \fBdraw3DTabButton\fP (\fBIGUIElement\fP *element, bool active, const \fBcore::rect\fP< s32 > &rect, const \fBcore::rect\fP< s32 > *clip=0)=0"
.br
.RI "\fIdraws a tab button \fP"
.ti -1c
.RI "virtual void \fBdraw3DTabBody\fP (\fBIGUIElement\fP *element, bool border, bool background, const \fBcore::rect\fP< s32 > &rect, const \fBcore::rect\fP< s32 > *clip=0)=0"
.br
.RI "\fIdraws a tab control body \fP"
.in -1c
.SH "Detailed Description"
.PP 
A skin modifies the look of the GUI elements. 
.PP
.SH "Member Function Documentation"
.PP 
.SS "virtual void engine::gui::IGUISkin::draw3DButtonPanePressed (\fBIGUIElement\fP * element, const \fBcore::rect\fP< s32 > & rect, const \fBcore::rect\fP< s32 > * clip = \fC0\fP)\fC [pure virtual]\fP"
.PP
draws a pressed 3d button pane 
.PP
Used for drawing for example buttons in pressed state. It uses the colors EGDC_3D_DARK_SHADOW, EGDC_3D_HIGH_LIGHT, EGDC_3D_SHADOW and EGDC_3D_FACE for this. See EGUI_DEFAULT_COLOR for details. 
.PP
\fBParameters:\fP
.RS 4
\fIelement,:\fP Pointer to the element which whiches to draw this. This parameter is usually not used by ISkin, but can be used for example by more complex implementations to find out how to draw the part exactly. 
.br
\fIrect,:\fP Defining area where to draw. 
.br
\fIclip,:\fP Clip area. 
.RE
.PP

.SS "virtual void engine::gui::IGUISkin::draw3DButtonPaneStandard (\fBIGUIElement\fP * element, const \fBcore::rect\fP< s32 > & rect, const \fBcore::rect\fP< s32 > * clip = \fC0\fP)\fC [pure virtual]\fP"
.PP
draws a standard 3d button pane 
.PP
Used for drawing for example buttons in normal state. It uses the colors EGDC_3D_DARK_SHADOW, EGDC_3D_HIGH_LIGHT, EGDC_3D_SHADOW and EGDC_3D_FACE for this. See EGUI_DEFAULT_COLOR for details. 
.PP
\fBParameters:\fP
.RS 4
\fIelement,:\fP Pointer to the element which whiches to draw this. This parameter is usually not used by ISkin, but can be used for example by more complex implementations to find out how to draw the part exactly. 
.br
\fIrect,:\fP Defining area where to draw. 
.br
\fIclip,:\fP Clip area. 
.RE
.PP

.SS "virtual void engine::gui::IGUISkin::draw3DMenuPane (\fBIGUIElement\fP * element, const \fBcore::rect\fP< s32 > & rect, const \fBcore::rect\fP< s32 > * clip = \fC0\fP)\fC [pure virtual]\fP"
.PP
draws a standard 3d menu pane 
.PP
Used for drawing for menus and context menus. It uses the colors EGDC_3D_DARK_SHADOW, EGDC_3D_HIGH_LIGHT, EGDC_3D_SHADOW and EGDC_3D_FACE for this. See EGUI_DEFAULT_COLOR for details. 
.PP
\fBParameters:\fP
.RS 4
\fIelement,:\fP Pointer to the element which whiches to draw this. This parameter is usually not used by ISkin, but can be used for example by more complex implementations to find out how to draw the part exactly. 
.br
\fIrect,:\fP Defining area where to draw. 
.br
\fIclip,:\fP Clip area. 
.RE
.PP

.SS "virtual void engine::gui::IGUISkin::draw3DSunkenPane (\fBIGUIElement\fP * element, \fBvideo::SColor\fP bgcolor, bool flat, bool fillBackGround, const \fBcore::rect\fP< s32 > & rect, const \fBcore::rect\fP< s32 > * clip = \fC0\fP)\fC [pure virtual]\fP"
.PP
draws a sunken 3d pane 
.PP
Used for drawing the background of edit, combo or check boxes. 
.PP
\fBParameters:\fP
.RS 4
\fIelement,:\fP Pointer to the element which whiches to draw this. This parameter is usually not used by ISkin, but can be used for example by more complex implementations to find out how to draw the part exactly. 
.br
\fIbgcolor,:\fP Background color. 
.br
\fIflat,:\fP Specifies if the sunken pane should be flat or displayed as sunken deep into the ground. 
.br
\fIfillBackGround,:\fP Specifies if the background should be filled with the background color or not be drawn at all. 
.br
\fIrect,:\fP Defining area where to draw. 
.br
\fIclip,:\fP Clip area. 
.RE
.PP

.SS "virtual void engine::gui::IGUISkin::draw3DTabBody (\fBIGUIElement\fP * element, bool border, bool background, const \fBcore::rect\fP< s32 > & rect, const \fBcore::rect\fP< s32 > * clip = \fC0\fP)\fC [pure virtual]\fP"
.PP
draws a tab control body 
.PP
\fBParameters:\fP
.RS 4
\fIelement,:\fP Pointer to the element which whiches to draw this. This parameter is usually not used by ISkin, but can be used for example by more complex implementations to find out how to draw the part exactly. 
.br
\fIborder,:\fP Specifies if the border should be drawn. 
.br
\fIbackground,:\fP Specifies if the background should be drawn. 
.br
\fIrect,:\fP Defining area where to draw. 
.br
\fIclip,:\fP Clip area. 
.RE
.PP

.SS "virtual void engine::gui::IGUISkin::draw3DTabButton (\fBIGUIElement\fP * element, bool active, const \fBcore::rect\fP< s32 > & rect, const \fBcore::rect\fP< s32 > * clip = \fC0\fP)\fC [pure virtual]\fP"
.PP
draws a tab button 
.PP
Used for drawing for tab buttons on top of tabs. 
.PP
\fBParameters:\fP
.RS 4
\fIelement,:\fP Pointer to the element which whiches to draw this. This parameter is usually not used by ISkin, but can be used for example by more complex implementations to find out how to draw the part exactly. 
.br
\fIactive,:\fP Specifies if the tab is currently active. 
.br
\fIrect,:\fP Defining area where to draw. 
.br
\fIclip,:\fP Clip area. 
.RE
.PP

.SS "virtual void engine::gui::IGUISkin::draw3DToolBar (\fBIGUIElement\fP * element, const \fBcore::rect\fP< s32 > & rect, const \fBcore::rect\fP< s32 > * clip = \fC0\fP)\fC [pure virtual]\fP"
.PP
draws a standard 3d tool bar 
.PP
Used for drawing for toolbars and menus. 
.PP
\fBParameters:\fP
.RS 4
\fIelement,:\fP Pointer to the element which whiches to draw this. This parameter is usually not used by ISkin, but can be used for example by more complex implementations to find out how to draw the part exactly. 
.br
\fIrect,:\fP Defining area where to draw. 
.br
\fIclip,:\fP Clip area. 
.RE
.PP

.SS "virtual \fBcore::rect\fP<s32> engine::gui::IGUISkin::draw3DWindowBackground (\fBIGUIElement\fP * element, bool drawTitleBar, \fBvideo::SColor\fP titleBarColor, const \fBcore::rect\fP< s32 > & rect, const \fBcore::rect\fP< s32 > * clip = \fC0\fP)\fC [pure virtual]\fP"
.PP
draws a window background 
.PP
Used for drawing the background of dialogs and windows. 
.PP
\fBParameters:\fP
.RS 4
\fIelement,:\fP Pointer to the element which whiches to draw this. This parameter is usually not used by ISkin, but can be used for example by more complex implementations to find out how to draw the part exactly. 
.br
\fItitleBarColor,:\fP Title color. 
.br
\fIdrawTitleBar,:\fP True to enable title drawing. 
.br
\fIrect,:\fP Defining area where to draw. 
.br
\fIclip,:\fP Clip area. 
.RE
.PP
\fBReturns:\fP
.RS 4
Returns rect where it would be good to draw title bar text. 
.RE
.PP

.SS "virtual const wchar_t* engine::gui::IGUISkin::getDefaultText (\fBEGUI_DEFAULT_TEXT\fP text)\fC [pure virtual]\fP"
.PP
Returns a default text. 
.PP
For example for Message box button captions: 'OK', 'Cancel', 'Yes', 'No' and so on. 
.SS "virtual void engine::gui::IGUISkin::setDefaultText (\fBEGUI_DEFAULT_TEXT\fP which, const wchar_t * newText)\fC [pure virtual]\fP"
.PP
Sets a default text. 
.PP
For example for Message box button captions: 'OK', 'Cancel', 'Yes', 'No' and so on. 

.SH "Author"
.PP 
Generated automatically by Doxygen for LTE 3D Engine from the source code.
