.TH "engine::video::SColor" 3 "29 Jul 2006" "LTE 3D Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine::video::SColor \- Class representing a 32 bit ARGB color.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <SColor.h>\fP
.PP
.SH "Detailed Description"
.PP 
Class representing a 32 bit ARGB color. 

The color values for red, green, blue and alpha are stored in a single s32. So all four values may be between 0 and 255. This class is used by most parts of the engine Engine to specify a color. An other way is using the class Colorf, which stores the color values in 4 floats. 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for LTE 3D Engine from the source code.
