.TH "engine::IEventReceiver" 3 "29 Jul 2006" "LTE 3D Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine::IEventReceiver \- Interface of an object wich can receive events.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <IEventReceiver.h>\fP
.PP
Inherited by \fBengine::gui::IGUIElement\fP, and \fBengine::scene::ICameraSceneNode\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBOnEvent\fP (\fBSEvent\fP event)=0"
.br
.RI "\fIcalled if an event happened. returns true if event was processed \fP"
.in -1c
.SH "Detailed Description"
.PP 
Interface of an object wich can receive events. 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for LTE 3D Engine from the source code.
