.TH "engine::core::dimension2d" 3 "29 Jul 2006" "LTE 3D Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine::core::dimension2d \- Specifies a 2 dimensional size.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <dimension2d.h>\fP
.PP
.SH "Detailed Description"
.PP 

.SS "template<class T> class engine::core::dimension2d< T >"
Specifies a 2 dimensional size. 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for LTE 3D Engine from the source code.
