.TH "engine::core::position2d" 3 "29 Jul 2006" "LTE 3D Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine::core::position2d \- Simple class for holding 2d coordinates.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <position2d.h>\fP
.PP
.SH "Detailed Description"
.PP 

.SS "template<class T> class engine::core::position2d< T >"
Simple class for holding 2d coordinates. 

Not supposed for doing geometric calculations. use \fBvector2d\fP instead for things like that. 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for LTE 3D Engine from the source code.
