.TH "engine::SEvent" 3 "29 Jul 2006" "LTE 3D Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine::SEvent \- Struct for holding event data. An event can be a gui, mouse or keyboard event.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <IEventReceiver.h>\fP
.PP
.SH "Detailed Description"
.PP 
Struct for holding event data. An event can be a gui, mouse or keyboard event. 
.PP
.SH "Member Data Documentation"
.PP 
.SS "f32 \fBengine::SEvent::Wheel\fP"
.PP
mouse wheel delta, usually 1.0 or -1.0. 
.PP
Only valid if event was EMIE_MOUSE_WHEEL 

.SH "Author"
.PP 
Generated automatically by Doxygen for LTE 3D Engine from the source code.
